name: Build Android APK

on:
  push:
    branches: [ "main", "develop" ] # Executa ao dar push nessas branches
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Ou '21', dependendo do seu projeto
        distribution: 'temurin'
        cache: gradle

    - name: Conceder permissão de execução ao gradlew
      run: chmod +x gradlew

    - name: Compilar APK (Debug)
      run: ./gradlew assembleDebug

    - name: Fazer upload do APK gerado
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
